TRUNCATE TABLE public.comment RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.post RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.account RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.users RESTART IDENTITY CASCADE;