spring:
  flyway:
    enabled: true
    default-schema: "public"
    locations: "classpath:db/migration"
    fail-on-missing-locations: true
    validateMigrationNaming: true
    schemas:
      - "public"