logging:
  level:
    ROOT: INFO
server:
  port: ${APP_PORT}
mail:
  from: "${MAIL_FROM}"
  host: "${MAIL_HOST}"
  port: "${MAIL_PORT}"
  username: "${MAIL_USERNAME}"
  password: "${MAIL_PASSWORD}"
cors:
  url: "${APP_URL:http://localhost:${server.port}}"
  pattern: "${APP_CORS_ORIGIN_PATTERN:http://localhost:${server.port}}"
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health"
      security:
        enabled: true
        username: "${ACTUATOR_USERNAME}"
        password: "${ACTUATOR_PASSWORD}"
options:
  jwt-settings:
    issuer: "tasos.daris"
    expirationInMinutes: "${JWT_EXPIRATION_IN_MINUTES:300}"
    secret: "${JWT_SECRET:sdfklgjndfk938475jkdfghw9345jkdfg}"
  db:
    secret: "${DB_SALT}"
spring:
  profiles:
    group:
      local:
      it:
      dev:
      production:
    active: ${SPRING_PROFILE:local, local-db}
  flyway:
    enabled: false
    default-schema: "public"
    locations: "classpath:db/migration"
    fail-on-missing-locations: true
    schemas:
      - "public"
  datasource:
    url: "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGCTL}?reWriteBatchedInserts=true"
    username: "${PGUSR}"
    password: "${PGPWD}"
    hikari:
      minimum-idle: 1
      maximum-pool-size: 40
      idle-timeout: 60000
      pool-name: "sociame-api-db-connection-pool"
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          sequence:
            increment_size_mismatch_strategy: EXCEPTION
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 4096
          fail_on_pagination_over_collection_fetch: true
        jdbc:
          batch_size: 50